#!/bin/sh
#
# Download, compile, and install the OpenBabel library.
# Requires git, cmake

CMAKE_FLAGS=

DIR=openbabel
BUILD_DIR=${DIR}-build

git clone git://github.com/openbabel/openbabel.git
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake ${CMAKE_FLAGS} ../${DIR}
make

CWD=`pwd`
cd ../${DIR}
# Comment off if the lib already exists
ln -s ${CWD}/lib lib
